### ISSUE TITLE
Connect wallet

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/multiclique-frontend#1]
Users should be able to connect with their (Freighter) wallet.

Once they are connected we will check whether their wallet already is a signer on a at least one Multiclique account.
Based on the outcome the following should happen:

- No MC account: Start the flow to create a new MC account
- One MC account: Redirect to the TX Overview page
- More than one MC account: Show a dropdown letting them select the MC account they want to be using, then redirect to the TX Overview page for that account

**Comment by hornilla-jowelyn** [comment]
Finished codifying screen

Todo:
Once data is available
- No MC account: Start the flow to create a new MC account
- One MC account: Redirect to the TX Overview page
- More than one MC account: Show a dropdown letting them select the MC account they want to be using, then redirect to the TX Overview page for that account

**Comment by GHesericsu** [comment]
This is done.
