### ISSUE TITLE
Create Multiclique account

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/multiclique-frontend#2]
Creating a new MC account requires the following:
- Adding all initial members (their name and wallet address)
- Setting the default threshold

- The current user will always be part of the initial members.
- The names and wallet addresses need to be stored in the backend (since the protocol doesn't know real names; only wallet addresses).
- The threshold must be from the range [1, no_of_members] - so for 5 members the valid thresholds are 1,2,3,4 and 5.
- If the input is valid, we will initialize a new MC contract - the address of the WASM is served from the backend.

**Comment by GHesericsu** [comment]
done
