### ISSUE TITLE
Add settings

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/multiclique-frontend#9]
In the "Settings" view there should be the following options:

- Add a signer
- Remove a signer
- Change the threshold
- Attach policy

This can recycle the view that we present during the account creation flow.
It is important that the threshold is always valid, i.e. it might have to be changed before removing a signer:

If there a 3 signers and the default threshold is set to 3 then removing a signer would brick the MC account since the default threshold can never be satisfied.

The protocol already prevents that scenario, but it would be nice if the frontend could already validate this.

The available policies should be provided by the backend (see https://github.com/deep-ink-ventures/elio-dao-service/issues/15).
The frontend can show a dropdown with the available and active policies.

When a policy is assigned, users need to provide the addresses (context) for which the policy is applicable.

**Comment by hornilla-jowelyn** [comment]
https://github.com/deep-ink-ventures/multiclique-frontend/pull/13

DONE:
- Codify screen

TODO: 
-  threshold validation
